### ISSUE TITLE
启动报错 Attempted import error: 'MOCK_MENU' is not exported from './config' (imported as 'config').

### ISSUE THREAD

**Issue by huahouye** [karakal-FET/react-admin#107]
环境 Macos，各个软件版本如下：
```
yarn -v
1.22.0

## node js 8 一样不行
node -v
v14.2.0

tsc -v
Version 3.9.2

yarn -v
1.22.0
```

按照 README 指引操作：
```
npm i -g saigao
saigao tmp-react-admin
cd tmp-react-admin
yarn
yarn start
```

启动报错：
```
Failed to compile.

./src/axios/index.ts
Attempted import error: 'MOCK_MENU' is not exported from './config' (imported as 'config').
```

请问哪里需要改动吗？还是我的环境有问题？或者哪里有文档？谢谢！

**Comment by yezihaohao** [comment]
问题已修复，请升级saigao最新版使用

**Comment by huahouye** [comment]
更新到最新版本的 saigao 依旧报错，日志如下：

```
huahouye-MacBook-Pro:admin-tool houyehua$ npm i -g saigao
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
/usr/local/bin/saigao -> /usr/local/lib/node_modules/saigao/bin/saigao.js
+ saigao@1.1.3
updated 1 package in 7.059s




huahouye-MacBook-Pro:admin-tool houyehua$ saigao tmp-react-admin
internal/modules/cjs/loader.js:1023
  throw err;
  ^

Error: Cannot find module '../dist/saigao.min.js'
Require stack:
- /usr/local/lib/node_modules/saigao/bin/saigao.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/saigao/bin/saigao.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/lib/node_modules/saigao/bin/saigao.js' ]
}




huahouye-MacBook-Pro:admin-tool houyehua$ ll /usr/local/lib/node_modules/saigao/bin/saigao.js
-rwxr-xr-x  1 houyehua  wheel  53  5 23 11:29 /usr/local/lib/node_modules/saigao/bin/saigao.js
```
